[workspace]
members = [
  "src", 
  "src/core",
  "src/ui",
  "src/audio",
]
resolver = "2"

[workspace.dependencies]
anyhow = "1"
async-trait = "0.1"
tokio = { version = "1.27", features = [ "full" ]}
tracing = "0.1"
