[package]
name = "zankyou"
version = "0.1.0"
edition = "2024"
license = "Apache-2.0"

[dependencies]
core.path = "core"
audio.path = "audio"
ui.path = "ui"
tokio.workspace = true
anyhow.workspace = true
tracing.workspace = true
